HOORY-5704 Change field_metadata to form fields and field options
hoory-com/chat-integrations pull request #23
Opened 2023-01-30 15:10 UTC by ArtyomFahradyan

2023-01-31 22:02 UTC, sayjeyhi requested changes

2023-01-31 22:02 UTC, sayjeyhi commented on .eslintrc.js
> +    sourceType: "module",
@ArtyomFahradyan jan, plz use `@hoory/eslint-config-react` package from npm, cuz we need to have one single way of coding everywhere, I open-sourced that one as well.

If you can, Update all other apps to use the same package

2023-02-02 08:29 UTC, ArtyomFahradyan commented on .eslintrc.js
> +    sourceType: "module",
done

2023-02-02 12:35 UTC, sayjeyhi approved these changes

2023-02-02 12:35 UTC, merged